services:
  billbatch:
    container_name: billbatch
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - proxy
      - rede_interna
    env_file: 
      - .env
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "rm -f public/storage &&
             php artisan storage:link &&
             php artisan migrate --force &&
             apache2-foreground"

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME} 
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /srv/data/mysql:/var/lib/mysql
    networks:
      - rede_interna
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis:8.10-alpine
    volumes:
      - /srv/data/redis:/data
    networks:
        - rede_interna
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD","redis-cli",'ping']
      interval: 5s
      timeout: 5s
      retries: 5
  
  mailpit:
    image: axllent/mailpit:v1.30.6
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - proxy
      - rede_interna
    healthcheck:
      test: ["CMD", "/mailpit","readyz"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s


# ------------------------------------------------------------

networks:
  rede_interna:
    driver: bridge
    internal: true
  proxy:
    driver: bridge