services:
  billbatch:
    image: billbatch-app:latest
    container_name: billbatch
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - proxy
      - rede_interna
    env_file: 
      - .env
    ports:
      - 8080:80
      - 5173:5173
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "rm -f public/storage &&
            php artisan storage:link &&
            php artisan migrate --force &&
            apache2-foreground"
        labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.billbatch.rule=Host(`billbatch.arthurssrichard.com`)"
      - "traefik.http.routers.billbatch.entrypoints=websecure"
      - "traefik.http.routers.billbatch.tls=true"
      - "traefik.http.routers.billbatch.service=billbatch"
      - "traefik.http.routers.billbatch.middlewares=security-headers@file,compress@file"

      - "traefik.http.services.billbatch.loadbalancer.server.port=80"

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME} 
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /srv/data/mysql:/var/lib/mysql
    networks:
      - rede_interna
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis:8.10-alpine
    volumes:
      - /srv/data/redis:/data
    networks:
        - rede_interna
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD","redis-cli",'ping']
      interval: 5s
      timeout: 5s
      retries: 5
  
  horizon:
    container_name: horizon
    build:
      context: .
      dockerfile: Dockerfile
    image: billbatch-app:latest
    restart: unless-stopped
    networks:
      - rede_interna
    healthcheck:
      test: ["CMD", "php", "artisan", "horizon:status"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      billbatch:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: []
    command: php artisan horizon

  mailpit:
    image: axllent/mailpit:v1.30.6
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - proxy
      - rede_interna
    healthcheck:
      test: ["CMD", "/mailpit","readyz"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s


# ------------------------------------------------------------

networks:
  proxy:
    external: true
  rede_interna:
    driver: bridge
    