name: Continuous Integration

on: 
  push:
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose up -d mysql
      - run: docker compose build billbatch
      - run: docker compose run --rm billbatch composer install
      - run: docker compose run --rm billbatch ./vendor/bin/pint --test
      - run: docker compose run --rm billbatch ./vendor/bin/pest
